<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.2.4 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Sat, 02 Jan 2010 18:02:25 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: FathomDB [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'FathomDB';
$cfg['Servers'][$i]['host'] = 'db12621-private.mysql.fathomdb.com';
$cfg['Servers'][$i]['port'] = 12621;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'BPobsqNcYYR0tZVQ';
$cfg['Servers'][$i]['nopassword'] = true;
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* rajk - for blobstreaming */
$cfg['Servers'][$i]['bs_garbage_threshold'] = 50;
$cfg['Servers'][$i]['bs_repository_threshold'] = '32M';
$cfg['Servers'][$i]['bs_temp_blob_timeout'] = 600;
$cfg['Servers'][$i]['bs_temp_log_threshold'] = '32M';

/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = false;
$cfg['blowfish_secret'] = '4b3f885473b459.71591068';
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
?>
